// Copyright 2023-2024, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import type LocalizedStringProperty from '../../chipper/js/LocalizedStringProperty.js';
import projectileDataLab from './projectileDataLab.js';

type StringsType = {
  'projectile-data-lab': {
    'titleStringProperty': LocalizedStringProperty;
  };
  'screen': {
    'variabilityStringProperty': LocalizedStringProperty;
    'sourcesStringProperty': LocalizedStringProperty;
    'measuresStringProperty': LocalizedStringProperty;
    'samplingStringProperty': LocalizedStringProperty;
  };
  'singleStringProperty': LocalizedStringProperty;
  'launchStringProperty': LocalizedStringProperty;
  'stopStringProperty': LocalizedStringProperty;
  'continuousStringProperty': LocalizedStringProperty;
  'noAirResistanceStringProperty': LocalizedStringProperty;
  'configurationStringProperty': LocalizedStringProperty;
  'projectileStringProperty': LocalizedStringProperty;
  'launcherNumberPatternStringProperty': LocalizedStringProperty;
  'angleStabilizerStringProperty': LocalizedStringProperty;
  'narrowStringProperty': LocalizedStringProperty;
  'wideStringProperty': LocalizedStringProperty;
  'mysteryLauncherStringProperty': LocalizedStringProperty;
  'customLauncherStringProperty': LocalizedStringProperty;
  'histogramStringProperty': LocalizedStringProperty;
  'fieldNumberPatternStringProperty': LocalizedStringProperty;
  'noDataStringProperty': LocalizedStringProperty;
  'meanStringProperty': LocalizedStringProperty;
  'standardDeviationStringProperty': LocalizedStringProperty;
  'valuesStringProperty': LocalizedStringProperty;
  'sampleSizeNStringProperty': LocalizedStringProperty;
  'pathsStringProperty': LocalizedStringProperty;
  'speedStringProperty': LocalizedStringProperty;
  'launchSpeedStringProperty': LocalizedStringProperty;
  'angleStringProperty': LocalizedStringProperty;
  'launchAngleStringProperty': LocalizedStringProperty;
  'measuringTapeStringProperty': LocalizedStringProperty;
  'stopwatchStringProperty': LocalizedStringProperty;
  'intervalToolStringProperty': LocalizedStringProperty;
  'meanEqualsValueMPatternStringProperty': LocalizedStringProperty;
  'meanXBarEqualsValueMPatternStringProperty': LocalizedStringProperty;
  'standardDeviationMPatternStringProperty': LocalizedStringProperty;
  'standardDeviationEqualsValueMPatternStringProperty': LocalizedStringProperty;
  'standardErrorOfXBarEqualsValueMPatternStringProperty': LocalizedStringProperty;
  'valueMetersPerSecondPatternStringProperty': LocalizedStringProperty;
  'valueDegreesPatternStringProperty': LocalizedStringProperty;
  'nEqualsSampleSizePatternStringProperty': LocalizedStringProperty;
  'sampleNumberOfCountPatternStringProperty': LocalizedStringProperty;
  'numberOfCountPatternStringProperty': LocalizedStringProperty;
  'binWidthMPatternStringProperty': LocalizedStringProperty;
  'intervalMPatternStringProperty': LocalizedStringProperty;
  'meanMPatternStringProperty': LocalizedStringProperty;
  'distanceStringProperty': LocalizedStringProperty;
  'meanDistanceStringProperty': LocalizedStringProperty;
  'countStringProperty': LocalizedStringProperty;
  'binWidthStringProperty': LocalizedStringProperty;
  'totalBinsStringProperty': LocalizedStringProperty;
  'histogramBinsStringProperty': LocalizedStringProperty;
  'histogramBinsPreferenceDescriptionStringProperty': LocalizedStringProperty;
  'showStandardErrorStringProperty': LocalizedStringProperty;
  'showStandardErrorPreferenceDescriptionStringProperty': LocalizedStringProperty;
  'launchSoundStringProperty': LocalizedStringProperty;
  'noneStringProperty': LocalizedStringProperty;
  'launchSoundPreferenceDescriptionStringProperty': LocalizedStringProperty;
  'percentPatternStringProperty': LocalizedStringProperty;
  'sampleSizeNPatternStringProperty': LocalizedStringProperty;
  'numberOfSamplesPatternStringProperty': LocalizedStringProperty;
  'fromAnywhereInSimStringProperty': LocalizedStringProperty;
  'showField1Through6StringProperty': LocalizedStringProperty;
  'creatingStringProperty': LocalizedStringProperty;
  'launchOrStopProjectilesStringProperty': LocalizedStringProperty;
  'autoGenerateDataStringProperty': LocalizedStringProperty;
  'autoGenerateDataPreferenceDescriptionStringProperty': LocalizedStringProperty;
  'projectileTypeAffectsSpeedStringProperty': LocalizedStringProperty;
  'projectileTypeAffectsSpeedPreferenceDescriptionStringProperty': LocalizedStringProperty;
  'keyboardHelpDialog': {
    'measuresScreen': {
      'movePointerIntervalHandleOrIntervalBlockStringProperty': LocalizedStringProperty;
      'objectStringProperty': LocalizedStringProperty;
      'moveStringProperty': LocalizedStringProperty;
      'endOfNumberLineStringProperty': LocalizedStringProperty;
      'startOfNumberLineStringProperty': LocalizedStringProperty;
    }
  }
};

const ProjectileDataLabStrings = getStringModule( 'PROJECTILE_DATA_LAB' ) as StringsType;

projectileDataLab.register( 'ProjectileDataLabStrings', ProjectileDataLabStrings );

export default ProjectileDataLabStrings;
