// Copyright 2023-2024, University of Colorado Boulder

/**
 * SimulationPreferencesContentNode displays general controls that globally affect the presentation or behavior of the simulation.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */

import { Node, Rectangle, RichText } from '../../../../scenery/js/imports.js';
import PreferencesControl from '../../../../joist/js/preferences/PreferencesControl.js';
import PreferencesDialogConstants from '../../../../joist/js/preferences/PreferencesDialogConstants.js';
import Tandem from '../../../../tandem/js/Tandem.js';
import PreferencesPanelContentNode from '../../../../joist/js/preferences/PreferencesPanelContentNode.js';
import { BinStrategy } from '../BinStrategy.js';
import { AUTO_GENERATE_DATA_PROPERTY, BIN_STRATEGY_PROPERTY, PROJECTILE_TYPE_AFFECTS_SPEED_PROPERTY } from '../PDLQueryParameters.js';
import PDLText from './PDLText.js';
import VerticalAquaRadioButtonGroup from '../../../../sun/js/VerticalAquaRadioButtonGroup.js';
import projectileDataLab from '../../projectileDataLab.js';
import { PDLPanel } from './PDLPanel.js';
import ProjectileDataLabStrings from '../../ProjectileDataLabStrings.js';
import { Checkbox } from '../../../../sun/js/imports.js';

export default class SimulationPreferencesContentNode extends PreferencesPanelContentNode {

  public constructor( parentNode: Node, tandem: Tandem ) {

    const autoGenerateDataControlTandem = tandem.createTandem( 'autoGenerateDataControl' );
    const projectileTypeAffectsSpeedControlTandem = tandem.createTandem( 'projectileTypeAffectsSpeedControl' );
    const binStrategyControlTandem = tandem.createTandem( 'binStrategyControl' );

    const binTypeRadioButtonGroup = new PDLPanel( new VerticalAquaRadioButtonGroup<BinStrategy>( BIN_STRATEGY_PROPERTY, [ {
      createNode: () => new PDLText( ProjectileDataLabStrings.binWidthStringProperty, { maxWidth: 200 } ),
      value: 'binWidth',
      tandemName: 'binWidthRadioButton'
    }, {
      createNode: () => new PDLText( ProjectileDataLabStrings.totalBinsStringProperty, { maxWidth: 200 } ),
      value: 'totalBins',
      tandemName: 'totalBinsRadioButton'
    } ], {
      tandem: binStrategyControlTandem.createTandem( 'radioButtonGroup' ),
      isDisposable: false,

      // Hide or show the entire row, not just one radio button
      phetioVisiblePropertyInstrumented: false
    } ) );

    const autoGenerateDataControl = new PreferencesControl( {
      tandem: autoGenerateDataControlTandem,
      labelNode: new PDLText( ProjectileDataLabStrings.autoGenerateDataStringProperty, PreferencesDialogConstants.CONTROL_LABEL_OPTIONS ),
      descriptionNode: new RichText( ProjectileDataLabStrings.autoGenerateDataPreferenceDescriptionStringProperty, PreferencesDialogConstants.CONTROL_DESCRIPTION_OPTIONS ),
      controlNode: new Checkbox( AUTO_GENERATE_DATA_PROPERTY,

        // Invisible icon
        new Rectangle( 0, 0, 1, 1, {
          fill: null,
          stroke: null
        } ), {
          tandem: autoGenerateDataControlTandem.createTandem( 'autoGenerateDataCheckbox' )
        } )
    } );

    const projectileTypeAffectsSpeedControl = new PreferencesControl( {
      tandem: projectileTypeAffectsSpeedControlTandem,
      labelNode: new PDLText( ProjectileDataLabStrings.projectileTypeAffectsSpeedStringProperty, PreferencesDialogConstants.CONTROL_LABEL_OPTIONS ),
      descriptionNode: new RichText( ProjectileDataLabStrings.projectileTypeAffectsSpeedPreferenceDescriptionStringProperty, PreferencesDialogConstants.CONTROL_DESCRIPTION_OPTIONS ),
      controlNode: new Checkbox( PROJECTILE_TYPE_AFFECTS_SPEED_PROPERTY,

        // Invisible icon
        new Rectangle( 0, 0, 1, 1, {
          fill: null,
          stroke: null
        } ), {
          tandem: projectileTypeAffectsSpeedControlTandem.createTandem( 'projectileTypeAffectsSpeedCheckbox' )
        } )
    } );

    const binStrategyControl = new PreferencesControl( {
      labelNode: new PDLText( ProjectileDataLabStrings.histogramBinsStringProperty, PreferencesDialogConstants.CONTROL_LABEL_OPTIONS ),
      descriptionNode: new RichText( ProjectileDataLabStrings.histogramBinsPreferenceDescriptionStringProperty, PreferencesDialogConstants.CONTROL_DESCRIPTION_OPTIONS ),
      controlNode: binTypeRadioButtonGroup,
      tandem: binStrategyControlTandem,
      phetioFeatured: true,
      visiblePropertyOptions: {
        phetioFeatured: true
      }
    } );

    super( {
      fill: 'white',
      content: [
        autoGenerateDataControl,
        projectileTypeAffectsSpeedControl,
        binStrategyControl
      ]
    } );
  }
}

projectileDataLab.register( 'SimulationPreferencesContentNode', SimulationPreferencesContentNode );